import Header from "@/ui/header";
import Footer from "@/ui/footer";

// These styles apply to every route in the application
import "./globals.css";

export const metadata = {
  title: "Oregon Web Press",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body >
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}
